### ISSUE TITLE
Game crashes when starting a race after latest update.

### ISSUE THREAD

**Issue by Pizzahut20** [Eddlm/autosport-racing-system-gta#2]
Hello!

As of the latest Drug Wars update, ARS keeps crashing when starting a race. Specifically when it's loading the track at 99%. Multiple people on the mod page have also mentioned this issue.

I'm kindly asking you to possibly fix this issue as the mod is currently unusable. It would be very much appreciated.

Thanks!

**Comment by Eddlm** [comment]
I have this issue myself. It seems to be related to memory offsets for the handling having changed and crashing it.

Working on it

**Comment by Teslahaha** [comment]
I've checked the log and found some interesting errors just seconds before the crash... could these be the culprit?

[2/27/2023 12:13:40 AM](Info): Loading Racer: BANSHEE2
**[2/27/2023 12:13:41 AM](Fatal): Driver ped is not spawning, requesting again.
[2/27/2023 12:13:42 AM](Fatal): Driver ped is not spawning, requesting again.
[2/27/2023 12:13:43 AM](Fatal): Driver ped is not spawning, requesting again.
[2/27/2023 12:13:44 AM](Fatal): Driver ped is not spawning, requesting again.
[2/27/2023 12:13:46 AM](Fatal): Driver ped is not spawning, requesting again.**
[2/27/2023 12:13:46 AM](Info): Loading Racer: BANSHEE2
[2/27/2023 12:13:47 AM](Info): Loading Racer: ISSI7
[2/27/2023 12:13:48 AM](Info): Loading Racer: BANSHEE2
[2/27/2023 12:13:48 AM](Info): Loading Racer: TYRUS
[2/27/2023 12:13:49 AM](Info): Loading Racer: BANSHEE2
[2/27/2023 12:13:49 AM](Info): Loading Racer: BANSHEE2
[2/27/2023 12:13:50 AM](Info): Loading Racer: ISSI7
[2/27/2023 12:13:50 AM](Info): Loading Racer: BANSHEE2
[2/27/2023 12:13:50 AM](Info): Loading Racer: TYRUS
[2/27/2023 12:13:50 AM](Info): Loading Racer: BANSHEE2
[2/27/2023 12:13:51 AM](Info): Loading Racer: BANSHEE2
[2/27/2023 12:13:51 AM](Info): Loading Racer: ISSI7
[2/27/2023 12:13:51 AM](Info): Loading Racer: BANSHEE2
[2/27/2023 12:13:51 AM](Info): Loading Racer: TYRUS

**Comment by Pizzahut20** [comment]
@Eddlm Apologies if I come across as annoying, I'm just wondering about the status of the progress as I and others would really love to be able to play with this script on the most recent patch again. :)

**Comment by rayvenz3** [comment]
@Eddlm is there any progress on the update? Sorry for bothering you

**Comment by Eddlm** [comment]
@Pizzahut20 @rayvenz3 @Teslahaha 
Released 0.8.5, should fix the crashes entirely.
Was trying to get the other features up to standard before getting it out. Let me know if its fixed for you uys

**Comment by Pizzahut20** [comment]
@Eddlm It's working now, thank you so much for fixing this :)

One thing I've noticed tho, the 'some cars are not bothering to brake because of downforce calculations' (iirc? , can't find the discussion back in 5mods discord) problem is back. Tested with the Zorrusso again, the racer is not even bothering to brake at corners and keeps crashing into walls.

All ini's in zip attachment, besides personalities since those are unchanged. edit: memoryoffsets are also unchanged
[ARS ini's.zip](https://github.com/Eddlm/autosport-racing-system-gta/files/11472897/ARS.ini.s.zip)

Haven't seen anything else besides the known stuff. 

Again, thank you very much for updating this! I'm already glad that it's working again.

**Comment by Eddlm** [comment]
Entirely forgot, that's because it uses new downforce mechanics whose values ARS interprets as incredibly high downforce. Can't test now, see if this build fixes it.
[bd2542-ARS.zip](https://github.com/Eddlm/autosport-racing-system-gta/files/11472972/bd2542-ARS.zip)

**Comment by rayvenz3** [comment]
> Entirely forgot, that's because it uses new downforce mechanics whose values ARS interprets as incredibly high downforce. Can't test now, see if this build fixes it. [bd2542-ARS.zip](https://github.com/Eddlm/autosport-racing-system-gta/files/11472972/bd2542-ARS.zip)

I downloaded and launched it but it seems to not work, I can't bring up the ARS menu despite it being Shift + Context action, can't use the arsmenu cheat eitheer. I'm using SHVDN v3.6.0 @Eddlm

**Comment by rayvenz3** [comment]
[Log.log](https://github.com/Eddlm/autosport-racing-system-gta/files/11475217/Log.log)

it only loads this much then just stops, menu won't load in or using cheat code either. Tried refreshing but nothing either

**Comment by rayvenz3** [comment]
[ScriptHookVDotNet.log](https://github.com/Eddlm/autosport-racing-system-gta/files/11475369/ScriptHookVDotNet.log)

Here's my dotnet log, ARS is giving out fatal errors @Eddlm do u know whats causing it?

**Comment by Pizzahut20** [comment]
> Entirely forgot, that's because it uses new downforce mechanics whose values ARS interprets as incredibly high downforce. Can't test now, see if this build fixes it. [bd2542-ARS.zip](https://github.com/Eddlm/autosport-racing-system-gta/files/11472972/bd2542-ARS.zip)

@Eddlm Unfortunately, it got worse. They're still not braking, and now they're also driving like it's a boat (they don't seem to turn fast enough), constantly going half off-track and therefore hitting props, walls, and trees. Tested with the same vehicle on the map Around Grapeseed 2, with the same ini's I sent you.

**Comment by rayvenz3** [comment]
@Eddlm idk if it's a me problem but idk why I can't save the car via the ARS menu anymore like the older version

**Comment by Pizzahut20** [comment]
Closing this as the original issue got fixed and it's going off-topic. Opened a new one about the downforce braking issue at: https://github.com/Eddlm/autosport-racing-system-gta/issues/3#issue-1717280751
